version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      context: ./Backend
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - ${API_PORT}:3030
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongodb://database:${DATABASE_PORT}
    links: 
      - database
    depends_on:
      - database

  database:
    image: 'mongo'
    volumes:
      - database:/data/db
    ports:
      - ${DATABASE_PORT}:27017

volumes:
  database: