export const CHECK_CREDENTIALS_SUCCESS = 'session/CHECK_CREDENTIALS_SUCCESS';
export const CHECK_CREDENTIALS_FAILED = 'session/CHECK_CREDENTIALS_FAILED';
export const CHECK_CREDENTIALS_LOADING = 'session/CHECK_CREDENTIALS_LOADING';
export const FETCH_LOGGED_USER_SUCCESS = 'session/FETCH_LOGGED_USER_SUCCESS';
export const LOG_OUT = 'session/LOG_OUT';
export const LOG_IN = 'session/LOG_IN';
